// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// read API key from --dart-define at compile time to avoid hardcoding secrets in source
const String _firebaseApiKey = String.fromEnvironment('FIREBASE_API_KEY', defaultValue: '');

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _firebaseApiKey,
    appId: '1:230339353147:web:a8ff4bbb49f7b6896d1a1e',
    messagingSenderId: '230339353147',
    projectId: 'gesi-halisi-acc8d',
    authDomain: 'gesi-halisi-acc8d.firebaseapp.com',
    storageBucket: 'gesi-halisi-acc8d.firebasestorage.app',
    measurementId: 'G-L6VLXQPNY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _firebaseApiKey,
    appId: '1:230339353147:android:902252d0b8915baa6d1a1e',
    messagingSenderId: '230339353147',
    projectId: 'gesi-halisi-acc8d',
    storageBucket: 'gesi-halisi-acc8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _firebaseApiKey,
    appId: '1:230339353147:ios:b233dd466630b4db6d1a1e',
    messagingSenderId: '230339353147',
    projectId: 'gesi-halisi-acc8d',
    storageBucket: 'gesi-halisi-acc8d.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _firebaseApiKey,
    appId: '1:230339353147:ios:b233dd466630b4db6d1a1e',
    messagingSenderId: '230339353147',
    projectId: 'gesi-halisi-acc8d',
    storageBucket: 'gesi-halisi-acc8d.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _firebaseApiKey,
    appId: '1:230339353147:web:b6aaefbabfd9a1156d1a1e',
    messagingSenderId: '230339353147',
    projectId: 'gesi-halisi-acc8d',
    authDomain: 'gesi-halisi-acc8d.firebaseapp.com',
    storageBucket: 'gesi-halisi-acc8d.firebasestorage.app',
    measurementId: 'G-JTBD6V1S39',
  );
}
